from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('actualites/', views.actualites_list, name='actualites_list'),
    path('actualites/<slug:slug>/', views.actualite_detail, name='actualite_detail'),
    path('gopi/', views.gopi_list, name='gopi_list'),
    path('gopi/<str:numero>/request/', views.gopi_request_form, name='gopi_request_form'),
    path('publications/', views.publications_list, name='publications_list'),
    path('publications/<slug:slug>/', views.publication_detail, name='publication_detail'),
    path('formations/', views.formations_list, name='formations_list'),
    path('formations/<slug:slug>/', views.formation_detail, name='formation_detail'),
    path('services/', views.services_list, name='services_list'),
    path('services/<slug:slug>/', views.service_detail, name='service_detail'),
    path('depot-marque/', views.depot_marque, name='depot_marque'),
    path('depot-brevet/', views.depot_brevet, name='depot_brevet'),
    path('depot-dessin-modele/', views.depot_dessin_modele, name='depot_dessin_modele'),
    path('depot-nom-commercial/', views.depot_nom_commercial, name='depot_nom_commercial'),
    path('documents/', views.documents_list, name='documents_list'),
    path('formation-request/', views.formation_request_form, name='formation_request_form'),
    path('documents/<int:pk>/', views.document_detail, name='document_detail'),
    path('formulaires/', views.formulaires, name='formulaires'),
    path('guides/', views.guides, name='guides'),
    path('legislation/', views.legislation, name='legislation'),
    path('faq/', views.faq, name='faq'),
    path('about/', views.about, name='about'),
    path('missions/', views.missions, name='missions'),
    path('organisation/', views.organisation, name='organisation'),
    path('contact/', views.contact, name='contact'),
    path('procedures/', views.procedures, name='procedures'),
    path('procedures-internationales/', views.procedures_internationales, name='procedures_internationales'),
    path('mandataires/', views.mandataires_list, name='mandataires_list'),
    path('renouvellement/<int:pk>/request/', views.renouvellement_request_form, name='renouvellement_request_form'),
    path('inscription-registre/<int:pk>/request/', views.inscription_registre_request_form, name='inscription_registre_request_form'),
    path('demandes/<int:pk>/detail/', views.demande_detail_ajax, name='demande_detail_ajax'),
    path('demandes/<int:pk>/edit/', views.edit_demande, name='edit_demande'),
    path('demandes/<int:pk>/delete/', views.delete_demande, name='delete_demande'),
    path('demandes/', views.liste_demandes, name='liste_demandes'),
    path('export-demandes/', views.export_demandes, name='export_demandes'),
]