# Generated by Django 5.2.5 on 2025-08-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=200, null=True)),
                ('formateurs', models.CharField(blank=True, max_length=250, null=True)),
                ('programme', models.FileField(blank=True, null=True, upload_to='programmes_formation/')),
                ('est_active', models.BooleanField(default=True, verbose_name='Formation active')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='GOPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Numéro de la GOPI')),
                ('date_publication', models.DateField(verbose_name='Date de publication')),
                ('fichier_pdf', models.FileField(upload_to='gopi/', verbose_name='Fichier PDF')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'GOPI',
                'verbose_name_plural': 'GOPI',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='publications/')),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('type_publication', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-date_publication'],
            },
        ),
    ]
