# Generated by Django 5.2.5 on 2025-08-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0002_formation_gopi_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTelechargeable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(upload_to='documents_telechargeables/')),
                ('type_document', models.CharField(blank=True, max_length=100, null=True)),
                ('date_publication', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Téléchargeable',
                'verbose_name_plural': 'Documents Téléchargeables',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('brevet', "Brevets d'Invention"), ('marque', 'Marques'), ('dessin_modele', 'Dessins & Modèles Industriels'), ('nom_commercial', 'Noms Commerciaux'), ('indication_geographique', 'Indications Géographiques')], max_length=100, unique=True, verbose_name='Nom du Service')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description_generale', models.TextField(verbose_name='Description Générale')),
                ('pourquoi_proteger', models.TextField(verbose_name='Pourquoi Protéger ?')),
                ('procedure_depot', models.TextField(verbose_name='Procédure de Dépôt/Enregistrement')),
                ('documents_requis', models.TextField(verbose_name='Documents Requis')),
                ('couts_tarifs', models.TextField(blank=True, null=True, verbose_name='Coûts & Tarifs')),
                ('faq', models.TextField(blank=True, null=True, verbose_name='Foire Aux Questions')),
            ],
            options={
                'verbose_name': 'Service de Propriété Intellectuelle',
                'verbose_name_plural': 'Services de Propriété Intellectuelle',
            },
        ),
    ]
