# Generated by Django 5.2.5 on 2025-08-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0003_documenttelechargeable_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttelechargeable',
            name='type_document',
            field=models.CharField(blank=True, choices=[('formulaire', 'Formulaire'), ('guide', 'Guide'), ('rapport', 'Rapport'), ('legislation', 'Législation')], max_length=100, null=True),
        ),
    ]
