# Generated by Django 5.2.5 on 2025-08-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0004_alter_documenttelechargeable_type_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='type_formation',
            field=models.CharField(choices=[('general', 'Général'), ('brevets', 'Brevets'), ('marques', 'Marques'), ('dessins_modeles', 'Dessins & Modèles'), ('contentieux', 'Contentieux PI'), ('valorisation', 'Valorisation PI')], default='general', max_length=50, verbose_name='Type de Formation'),
        ),
    ]
