# Generated by Django 5.2.5 on 2025-08-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0005_formation_type_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='duree_heures',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Durée en Heures'),
        ),
        migrations.AddField(
            model_name='formation',
            name='image_presentation',
            field=models.ImageField(blank=True, null=True, upload_to='formations/', verbose_name='Image de Présentation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='modalites_inscription',
            field=models.TextField(blank=True, null=True, verbose_name="Modalités d'Inscription"),
        ),
        migrations.AddField(
            model_name='formation',
            name='objectifs_apprentissage',
            field=models.TextField(blank=True, null=True, verbose_name="Objectifs d'Apprentissage"),
        ),
        migrations.AddField(
            model_name='formation',
            name='prix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Coût'),
        ),
        migrations.AddField(
            model_name='formation',
            name='public_cible',
            field=models.TextField(blank=True, null=True, verbose_name='Public Cible'),
        ),
    ]
