# Generated by Django 5.2.5 on 2025-08-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0006_formation_duree_heures_formation_image_presentation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_annonce', models.CharField(choices=[('nouveau', 'Nouveau'), ('info', 'Info'), ('alerte', 'Alerte')], default='info', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('lien', models.URLField(blank=True, null=True)),
                ('texte_lien', models.CharField(blank=True, max_length=50, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Annonce Défilante',
                'verbose_name_plural': 'Annonces Défilantes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la Statistique')),
                ('valeur', models.CharField(max_length=50, verbose_name='Valeur (ex: +44 000)')),
                ('icone_fa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icône Font Awesome (ex: fas fa-trademark)')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Statistique Clé',
                'verbose_name_plural': 'Statistiques Clés',
                'ordering': ['ordre'],
            },
        ),
    ]
