# Generated by Django 5.2.5 on 2025-08-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0007_annonce_statistique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_slides/')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('lien', models.URLField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Slide de Carrousel',
                'verbose_name_plural': 'Slides de Carrousel',
                'ordering': ['ordre'],
            },
        ),
    ]
