# Generated by Django 5.2.5 on 2025-08-22 05:58

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0008_carouselslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeActualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('couleur', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'verbose_name': "Type d'Actualité",
                'verbose_name_plural': "Types d'Actualités",
            },
        ),
        migrations.AddField(
            model_name='actualite',
            name='type_actualite_old',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='type_actualite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualites', to='content_management.typeactualite'),
        ),
    ]
