# Generated by Django 5.2.5 on 2025-08-22 05:58

from django.db import migrations
from django.apps import apps as global_apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

def create_typeactualite(apps: global_apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Actualite = apps.get_model('content_management', 'Actualite')
    TypeActualite = apps.get_model('content_management', 'TypeActualite')

    TYPE_DATA = {
        'article': {'nom': 'Article de blog', 'couleur': '#4299E1'}, # Bleu
        'communique': {'nom': 'Communiqué de presse', 'couleur': '#F6AD55'}, # Orange
        'evenement': {'nom': 'Annonce d\'événement', 'couleur': '#667EEA'}, # Indigo
        'formation': {'nom': 'Formation', 'couleur': '#48BB78'}, # Vert
        'guide': {'nom': 'Guide', 'couleur': '#ECC94B'}, # Jaune
        'legislation': {'nom': 'Législation', 'couleur': '#9F7AEA'}, # Violet
        'evenement_special': {'nom': 'Événement Spécial', 'couleur': '#ED8936'}, # Orange foncé
    }

    for key, data in TYPE_DATA.items():
        type_obj, created = TypeActualite.objects.get_or_create(nom=data['nom'], defaults={'couleur': data['couleur']})
        Actualite.objects.filter(type_actualite_old=key).update(type_actualite=type_obj)

def reverse_typeactualite(apps: global_apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Actualite = apps.get_model('content_management', 'Actualite')
    TypeActualite = apps.get_model('content_management', 'TypeActualite')
    TypeActualite.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0009_typeactualite_actualite_type_actualite_old_and_more'),
    ]

    operations = [
        migrations.RunPython(create_typeactualite, reverse_typeactualite),
    ]
