# Generated by Django 5.2.5 on 2025-08-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0010_auto_20250822_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualite',
            name='type_actualite_old',
        ),
    ]
