# Generated by Django 5.2.5 on 2025-08-22 11:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0011_remove_actualite_type_actualite_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='contenu',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
