# Generated by Django 5.2.5 on 2025-08-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0012_alter_actualite_contenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('numero_agrement', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="Numéro d'agrément")),
                ('date_agrement', models.DateField(blank=True, null=True, verbose_name="Date d'agrément")),
            ],
            options={
                'verbose_name': 'Mandataire',
                'verbose_name_plural': 'Mandataires',
                'ordering': ['nom'],
            },
        ),
    ]
