# Generated by Django 5.2.5 on 2025-08-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0013_mandataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandataire',
            name='qualite',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qualité'),
        ),
    ]
