# Generated by Django 5.2.5 on 2025-08-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0014_mandataire_qualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandataire',
            name='email_2',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email 2'),
        ),
        migrations.AddField(
            model_name='mandataire',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone 2'),
        ),
        migrations.AlterField(
            model_name='mandataire',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email 1'),
        ),
        migrations.AlterField(
            model_name='mandataire',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone 1'),
        ),
    ]
