# Generated by Django 5.2.5 on 2025-08-25 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0015_mandataire_email_2_mandataire_telephone_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='content_management.formation')),
            ],
            options={
                'verbose_name': 'Inscription Formation',
                'verbose_name_plural': 'Inscriptions Formations',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
