# Generated by Django 5.2.5 on 2025-08-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0016_inscriptionformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionRegistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_gopi', models.CharField(max_length=50, verbose_name='Numéro de la GOPI')),
                ('date_publication', models.DateField(verbose_name='Date de publication')),
                ('annee_depot_demande', models.IntegerField(verbose_name="Année de dépôt de la demande d'inscription")),
            ],
            options={
                'verbose_name': 'Inscription au Registre',
                'verbose_name_plural': 'Inscriptions au Registre',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Renouvellement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_edition', models.CharField(max_length=50, verbose_name='Numéro de l’édition')),
                ('date_publication', models.DateField(verbose_name='Date de publication')),
                ('annee_emission_certificat', models.IntegerField(verbose_name="Année d'émission du certificat de renouvellement")),
            ],
            options={
                'verbose_name': 'Renouvellement',
                'verbose_name_plural': 'Renouvellements',
                'ordering': ['-date_publication'],
            },
        ),
    ]
