# Generated by Django 5.2.5 on 2025-08-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0017_inscriptionregistre_renouvellement'),
    ]

    operations = [
        migrations.AddField(
            model_name='gopi',
            name='contient_brevet',
            field=models.BooleanField(default=False, verbose_name='Contient Brevet'),
        ),
        migrations.AddField(
            model_name='gopi',
            name='contient_dessin_modele',
            field=models.BooleanField(default=False, verbose_name='Contient Dessin ou Modèle'),
        ),
        migrations.AddField(
            model_name='gopi',
            name='contient_marque',
            field=models.BooleanField(default=False, verbose_name='Contient Marque'),
        ),
        migrations.AddField(
            model_name='gopi',
            name='contient_nom_commercial',
            field=models.BooleanField(default=False, verbose_name='Contient Nom Commercial'),
        ),
    ]
