# Generated by Django 5.2.5 on 2025-08-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0018_gopi_contient_brevet_gopi_contient_dessin_modele_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gopi',
            name='contient_brevet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Informations Brevet'),
        ),
        migrations.AlterField(
            model_name='gopi',
            name='contient_dessin_modele',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Informations Dessin ou Modèle'),
        ),
        migrations.AlterField(
            model_name='gopi',
            name='contient_marque',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Informations Marque'),
        ),
        migrations.AlterField(
            model_name='gopi',
            name='contient_nom_commercial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Informations Nom Commercial'),
        ),
    ]
