# Generated by Django 5.2.5 on 2025-08-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0019_alter_gopi_contient_brevet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gopi',
            name='description',
        ),
    ]
