# Generated by Django 5.2.5 on 2025-08-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0020_remove_gopi_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gopi',
            name='fichier_pdf',
        ),
    ]
