# Generated by Django 5.2.5 on 2025-08-27 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0021_remove_gopi_fichier_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('gopi', 'Demande GOPI'), ('renouvellement', 'Demande Renouvellement'), ('inscription_registre', 'Demande Inscription au Registre'), ('inscription_formation', 'Inscription Formation')], max_length=50, verbose_name='Type de Demande')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom Complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse E-mail')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de Soumission')),
                ('formation_concernee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_management.formation', verbose_name='Formation Concernée')),
                ('gopi_concernee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_management.gopi', verbose_name='GOPI Concernée')),
                ('inscription_registre_concernee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_management.inscriptionregistre', verbose_name='Inscription au Registre Concernée')),
                ('renouvellement_concerne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_management.renouvellement', verbose_name='Renouvellement Concerné')),
            ],
            options={
                'verbose_name': 'Demande Utilisateur',
                'verbose_name_plural': 'Demandes Utilisateur',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
