# Generated by Django 5.2.5 on 2025-08-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0022_demandeutilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeutilisateur',
            name='statut',
            field=models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours'), ('traitee', 'Traitée'), ('archivee', 'Archivée')], default='nouvelle', max_length=20, verbose_name='Statut'),
        ),
    ]
