# Generated by Django 5.2.5 on 2025-08-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0023_demandeutilisateur_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttelechargeable',
            name='categorie_pi',
            field=models.CharField(choices=[('marque', 'Marques'), ('brevet', 'Brevets'), ('dessin_modele', 'Dessins & Modèles Industriels'), ('nom_commercial', 'Noms Commerciaux'), ('indication_geographique', 'Indications Géographiques'), ('procedures_speciales', 'Procédures Spéciales'), ('general', 'Général / Divers')], default='general', max_length=50, verbose_name='Catégorie de Propriété Industrielle'),
        ),
    ]
