# Generated by Django 5.2.5 on 2025-08-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0024_documenttelechargeable_categorie_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttelechargeable',
            name='contenu_texte',
            field=models.TextField(blank=True, null=True, verbose_name='Contenu Texte (extrait du PDF)'),
        ),
        migrations.AddField(
            model_name='documenttelechargeable',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True), # Temporarily set null=True
        ),
    ]
