# Generated by Django 5.2.5 on 2025-08-28 12:19

from django.db import migrations, models
from django.utils.text import slugify

def ensure_unique_slugs(apps, schema_editor):
    DocumentTelechargeable = apps.get_model('content_management', 'DocumentTelechargeable')
    for doc in DocumentTelechargeable.objects.all():
        if not doc.slug:
            doc.slug = slugify(doc.titre)
        original_slug = doc.slug
        counter = 1
        while DocumentTelechargeable.objects.filter(slug=doc.slug).exclude(pk=doc.pk).exists():
            doc.slug = f"{original_slug}-{counter}"
            counter += 1
        doc.save() # Sauvegarde chaque objet individuellement

class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0025_documenttelechargeable_contenu_texte_and_more'),
    ]

    operations = [
        migrations.RunPython(ensure_unique_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='documenttelechargeable',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
