# Generated by Django 5.2.5 on 2025-08-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0026_add_slug_unique_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttelechargeable',
            name='contenu_texte',
        ),
    ]
